spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}?serverTimezone=Asia/Seoul
    username: ${MYSQL_NAME}
    password: ${MYSQL_PASSWORD}

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000  # 30초
      connection-timeout: 30000  # 30초
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  logging:
    level:
      root: INFO
      org.hibernate.SQL: WARN

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
